// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_APIpeliculas from "./routes/api/APIpeliculas.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $cookies from "./routes/cookies.tsx";
import * as $film_id_ from "./routes/film/[id].tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DetallesPeliculas from "./islands/DetallesPeliculas.tsx";
import * as $Filtros from "./islands/Filtros.tsx";
import * as $Home from "./islands/Home.tsx";
import * as $ListaPeliculas from "./islands/ListaPeliculas.tsx";
import * as $ModalPeliculas from "./islands/ModalPeliculas.tsx";
import * as $proyectos from "./islands/proyectos.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/APIpeliculas.ts": $api_APIpeliculas,
    "./routes/api/joke.ts": $api_joke,
    "./routes/cookies.tsx": $cookies,
    "./routes/film/[id].tsx": $film_id_,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/DetallesPeliculas.tsx": $DetallesPeliculas,
    "./islands/Filtros.tsx": $Filtros,
    "./islands/Home.tsx": $Home,
    "./islands/ListaPeliculas.tsx": $ListaPeliculas,
    "./islands/ModalPeliculas.tsx": $ModalPeliculas,
    "./islands/proyectos.tsx": $proyectos,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
